var projs=[{'name': 'NOVIQ',
    'desc': 'Your immersive music player with lyrics displaying, based on web. (Still updating)',
    'url': 'https://xolyn.github.io/noviq',
    'img': 'https://images.unsplash.com/photo-1565656898731-61d5df85f9a7?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'},
   {'name': 'YAFIWG',
    'desc': 'A simple file index webpage generator for static webpage hosting services like Github Pages, Cloudflare R2,...',
    'url': 'https://github.com/xolyn/yafiwg',
    'img': 'https://f.zly.vg/assets/yafiwg.jpg'},
   {'name': 'beamer2ppt',
    'desc': "Can't convert beamer into Powerpoint? Losing format and font after using all kinds of conversion tools? Try beamer2ppt, a python script converting LaTeX beamer in PDF file to PPT/PPTX file, perfectly maintaining formulae and slides formatting.",
    'url': 'https://github.com/xolyn/beamer2ppt',
    'img': 'https://f.zly.vg/assets/b2p.jpg'},
   {'name': 'Optimization plyaground',
    'desc': null,
    'url': 'https://xolyn.github.io/academic/opt.html',
    'img': 'https://images.unsplash.com/photo-1628268509381-c70293fa638d?q=80&w=2980&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'},
   {'name': 'Birthday paradox',
    'desc': 'Exploration of probability principles through simulation of a counterintuitive phenomenon.',
    'url': 'https://xolyn.github.io//academic/bp.html',
    'img': 'https://images.unsplash.com/photo-1669502067440-6a09729d072d?q=80&w=2000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'},
   {'name': 'CLI personal webpage',
    'desc': 'Tired of traditional graphic UX? Step into the realm of binary strings, where the CLI morphs into a digital canvas, echoing the rhythmic cadence of terminal commands! Embark on a journey where every command unlocks hidden treasures, revealing surprises that dance beneath the surface. ',
    'url': 'https://aqmn.github.io/cmd',
    'img': 'https://shorturl.at/anrE3'},
   {'name': 'Time Series Analysis',
    'desc': null,
    'url': 'https://xolyn.github.io/5999proj',
    'img': 'https://images.unsplash.com/photo-1700157710823-2e9e58414802?q=80&w=3132&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'},
   {'name': 'Gadgetz',
    'desc': 'Some predefined widgets for web, following minialism and user friendliness.',
    'url': 'https://xolyn.github.io/widgets/',
    'img': 'https://i.pinimg.com/originals/30/8d/fd/308dfd052f050d31b8c05c6a63c0831f.gif'},
   {'name': 'The bug index',
    'desc': "Discover the enigmatic world of entomology through the collection of insects' photographies. Although creepy, this digital compendium unveils the intricate beauty and complexity of various insect species. Immerse yourself in a realm where art meets nature, fostering a deeper appreciation for the microcosms that flourish around us.",
    'url': 'https://f.zly.vg/bug',
    'img': 'https://f.zly.vg/assets/bug.png'},
   {'name': 'Pseudo Lexicon',
    'desc': null,
    'url': 'https://xolyn.github.io/pslex',
    'img': 'https://images.unsplash.com/photo-1595325093677-422a41bcf51c?q=80&w=3270&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'},
   {'name': "Gambler's Ruin",
    'desc': 'In this digital playground, the abstract dance of probabilities comes to life, showcasing the delicate balance of fortune and risk. Watch as the threads of fate weave through peaks and nadirs, where a stories, and simulations are told and used to reveal the hidden patterns of seeming randomness.',
    'url': 'https://xolyn.github.io/grd.html',
    'img': 'https://images.unsplash.com/photo-1726004592905-dc5cd794bda6?q=80&w=2980&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'}]