site_name: ZDocs
nav:
  - Home: index.md
  - About: about.md
theme: readthedocs

# use_directory_urls: false
plugins:
  - search

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  - mdx_math

# markdown_extensions:
#   - pymdownx.arithmatex:
#       generic: true

# extra_javascript:
#   - javascripts/katex.js
#   - https://unpkg.com/katex@0/dist/katex.min.js
#   - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - docs/css/es.css